version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      lint:
        patterns:
          - "@stylistic/*"
          - "eslint-plugin-import-newlines"
          - "oxlint"
          - "oxlint-*"
      htmlparser2:
        patterns:
          - "htmlparser2"
          - "domhandler"
          - "domutils"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
